//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 02:40:04 PM UYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2000/09/xmldsig#",xmlns = { 
        @XmlNs(namespaceURI = "http://www.w3.org/2000/09/xmldsig#", prefix = "")
    }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openup.dgi.efactura.dto.org.w3._2000._09.xmldsig;
import javax.xml.bind.annotation.XmlNs;

