//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 02:31:58 PM UYT 
//


package org.openup.dgi.efactura.dto.uy.gub.dgi.cfe;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.openup.dgi.efactura.dto.org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for ACKCFEdefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ACKCFEdefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Caratula">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RUCReceptor" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="IDRespuesta">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="NomArch" type="{http://cfe.dgi.gub.uy}NomArchType"/>
 *                   &lt;element name="FecHRecibido" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                   &lt;element name="IDEmisor" type="{http://cfe.dgi.gub.uy}IDRecEmiType"/>
 *                   &lt;element name="IDReceptor" type="{http://cfe.dgi.gub.uy}IDRecEmiType"/>
 *                   &lt;element name="CantenSobre">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantResponden">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantCFEAceptados" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantCFERechazados" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantCFCAceptados" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantCFCObservados" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantOtrosRechazados" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Tmst" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ACKCFE_Det" maxOccurs="250">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Nro_ordinal" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="TipoCFE" type="{http://cfe.dgi.gub.uy}CFEType" minOccurs="0"/>
 *                   &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType" minOccurs="0"/>
 *                   &lt;element name="NroCFE" type="{http://cfe.dgi.gub.uy}NroCFEType" minOccurs="0"/>
 *                   &lt;element name="FechaCFE" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
 *                   &lt;element name="TmstCFE" type="{http://cfe.dgi.gub.uy}FechaHoraType" minOccurs="0"/>
 *                   &lt;element name="Estado">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}EstadoType">
 *                         &lt;enumeration value="AE"/>
 *                         &lt;enumeration value="BE"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MotivosRechazoCF" type="{http://cfe.dgi.gub.uy}RechazoCFE_PartesType" maxOccurs="10" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ACKCFEdefType", propOrder = {
    "caratula",
    "ackcfeDet",
    "signature"
})
public class ACKCFEdefType {

    @XmlElement(name = "Caratula", required = true)
    protected ACKCFEdefType.Caratula caratula;
    @XmlElement(name = "ACKCFE_Det", required = true)
    protected List<ACKCFEdefType.ACKCFEDet> ackcfeDet;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the caratula property.
     * 
     * @return
     *     possible object is
     *     {@link ACKCFEdefType.Caratula }
     *     
     */
    public ACKCFEdefType.Caratula getCaratula() {
        return caratula;
    }

    /**
     * Sets the value of the caratula property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACKCFEdefType.Caratula }
     *     
     */
    public void setCaratula(ACKCFEdefType.Caratula value) {
        this.caratula = value;
    }

    /**
     * Gets the value of the ackcfeDet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ackcfeDet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getACKCFEDet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ACKCFEdefType.ACKCFEDet }
     * 
     * 
     */
    public List<ACKCFEdefType.ACKCFEDet> getACKCFEDet() {
        if (ackcfeDet == null) {
            ackcfeDet = new ArrayList<ACKCFEdefType.ACKCFEDet>();
        }
        return this.ackcfeDet;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Nro_ordinal" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="TipoCFE" type="{http://cfe.dgi.gub.uy}CFEType" minOccurs="0"/>
     *         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType" minOccurs="0"/>
     *         &lt;element name="NroCFE" type="{http://cfe.dgi.gub.uy}NroCFEType" minOccurs="0"/>
     *         &lt;element name="FechaCFE" type="{http://cfe.dgi.gub.uy}FechaType" minOccurs="0"/>
     *         &lt;element name="TmstCFE" type="{http://cfe.dgi.gub.uy}FechaHoraType" minOccurs="0"/>
     *         &lt;element name="Estado">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}EstadoType">
     *               &lt;enumeration value="AE"/>
     *               &lt;enumeration value="BE"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="MotivosRechazoCF" type="{http://cfe.dgi.gub.uy}RechazoCFE_PartesType" maxOccurs="10" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nroOrdinal",
        "tipoCFE",
        "serie",
        "nroCFE",
        "fechaCFE",
        "tmstCFE",
        "estado",
        "motivosRechazoCF"
    })
    public static class ACKCFEDet {

        @XmlElement(name = "Nro_ordinal", required = true)
        protected BigInteger nroOrdinal;
        @XmlElement(name = "TipoCFE")
        protected BigInteger tipoCFE;
        @XmlElement(name = "Serie")
        protected String serie;
        @XmlElement(name = "NroCFE")
        protected BigInteger nroCFE;
        @XmlElement(name = "FechaCFE")
        protected XMLGregorianCalendar fechaCFE;
        @XmlElement(name = "TmstCFE")
        protected XMLGregorianCalendar tmstCFE;
        @XmlElement(name = "Estado", required = true)
        protected String estado;
        @XmlElement(name = "MotivosRechazoCF")
        protected List<RechazoCFEPartesType> motivosRechazoCF;

        /**
         * Gets the value of the nroOrdinal property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNroOrdinal() {
            return nroOrdinal;
        }

        /**
         * Sets the value of the nroOrdinal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNroOrdinal(BigInteger value) {
            this.nroOrdinal = value;
        }

        /**
         * Gets the value of the tipoCFE property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoCFE() {
            return tipoCFE;
        }

        /**
         * Sets the value of the tipoCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoCFE(BigInteger value) {
            this.tipoCFE = value;
        }

        /**
         * Gets the value of the serie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerie() {
            return serie;
        }

        /**
         * Sets the value of the serie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerie(String value) {
            this.serie = value;
        }

        /**
         * Gets the value of the nroCFE property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNroCFE() {
            return nroCFE;
        }

        /**
         * Sets the value of the nroCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNroCFE(BigInteger value) {
            this.nroCFE = value;
        }

        /**
         * Gets the value of the fechaCFE property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaCFE() {
            return fechaCFE;
        }

        /**
         * Sets the value of the fechaCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaCFE(XMLGregorianCalendar value) {
            this.fechaCFE = value;
        }

        /**
         * Gets the value of the tmstCFE property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstCFE() {
            return tmstCFE;
        }

        /**
         * Sets the value of the tmstCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstCFE(XMLGregorianCalendar value) {
            this.tmstCFE = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the motivosRechazoCF property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the motivosRechazoCF property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMotivosRechazoCF().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RechazoCFEPartesType }
         * 
         * 
         */
        public List<RechazoCFEPartesType> getMotivosRechazoCF() {
            if (motivosRechazoCF == null) {
                motivosRechazoCF = new ArrayList<RechazoCFEPartesType>();
            }
            return this.motivosRechazoCF;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RUCReceptor" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="IDRespuesta">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="NomArch" type="{http://cfe.dgi.gub.uy}NomArchType"/>
     *         &lt;element name="FecHRecibido" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *         &lt;element name="IDEmisor" type="{http://cfe.dgi.gub.uy}IDRecEmiType"/>
     *         &lt;element name="IDReceptor" type="{http://cfe.dgi.gub.uy}IDRecEmiType"/>
     *         &lt;element name="CantenSobre">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantResponden">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantCFEAceptados" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantCFERechazados" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantCFCAceptados" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantCFCObservados" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantOtrosRechazados" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Tmst" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rucReceptor",
        "rucEmisor",
        "idRespuesta",
        "nomArch",
        "fecHRecibido",
        "idEmisor",
        "idReceptor",
        "cantenSobre",
        "cantResponden",
        "cantCFEAceptados",
        "cantCFERechazados",
        "cantCFCAceptados",
        "cantCFCObservados",
        "cantOtrosRechazados",
        "tmst"
    })
    public static class Caratula {

        @XmlElement(name = "RUCReceptor", required = true)
        protected String rucReceptor;
        @XmlElement(name = "RUCEmisor", required = true)
        protected String rucEmisor;
        @XmlElement(name = "IDRespuesta", required = true)
        protected BigInteger idRespuesta;
        @XmlElement(name = "NomArch", required = true)
        protected String nomArch;
        @XmlElement(name = "FecHRecibido", required = true)
        protected XMLGregorianCalendar fecHRecibido;
        @XmlElement(name = "IDEmisor", required = true)
        protected BigInteger idEmisor;
        @XmlElement(name = "IDReceptor", required = true)
        protected BigInteger idReceptor;
        @XmlElement(name = "CantenSobre", required = true)
        protected BigInteger cantenSobre;
        @XmlElement(name = "CantResponden", required = true)
        protected BigInteger cantResponden;
        @XmlElement(name = "CantCFEAceptados")
        protected BigInteger cantCFEAceptados;
        @XmlElement(name = "CantCFERechazados")
        protected BigInteger cantCFERechazados;
        @XmlElement(name = "CantCFCAceptados")
        protected BigInteger cantCFCAceptados;
        @XmlElement(name = "CantCFCObservados")
        protected BigInteger cantCFCObservados;
        @XmlElement(name = "CantOtrosRechazados")
        protected BigInteger cantOtrosRechazados;
        @XmlElement(name = "Tmst", required = true)
        protected XMLGregorianCalendar tmst;

        /**
         * Gets the value of the rucReceptor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRUCReceptor() {
            return rucReceptor;
        }

        /**
         * Sets the value of the rucReceptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRUCReceptor(String value) {
            this.rucReceptor = value;
        }

        /**
         * Gets the value of the rucEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRUCEmisor() {
            return rucEmisor;
        }

        /**
         * Sets the value of the rucEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRUCEmisor(String value) {
            this.rucEmisor = value;
        }

        /**
         * Gets the value of the idRespuesta property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIDRespuesta() {
            return idRespuesta;
        }

        /**
         * Sets the value of the idRespuesta property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIDRespuesta(BigInteger value) {
            this.idRespuesta = value;
        }

        /**
         * Gets the value of the nomArch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNomArch() {
            return nomArch;
        }

        /**
         * Sets the value of the nomArch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNomArch(String value) {
            this.nomArch = value;
        }

        /**
         * Gets the value of the fecHRecibido property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFecHRecibido() {
            return fecHRecibido;
        }

        /**
         * Sets the value of the fecHRecibido property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFecHRecibido(XMLGregorianCalendar value) {
            this.fecHRecibido = value;
        }

        /**
         * Gets the value of the idEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIDEmisor() {
            return idEmisor;
        }

        /**
         * Sets the value of the idEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIDEmisor(BigInteger value) {
            this.idEmisor = value;
        }

        /**
         * Gets the value of the idReceptor property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIDReceptor() {
            return idReceptor;
        }

        /**
         * Sets the value of the idReceptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIDReceptor(BigInteger value) {
            this.idReceptor = value;
        }

        /**
         * Gets the value of the cantenSobre property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantenSobre() {
            return cantenSobre;
        }

        /**
         * Sets the value of the cantenSobre property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantenSobre(BigInteger value) {
            this.cantenSobre = value;
        }

        /**
         * Gets the value of the cantResponden property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantResponden() {
            return cantResponden;
        }

        /**
         * Sets the value of the cantResponden property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantResponden(BigInteger value) {
            this.cantResponden = value;
        }

        /**
         * Gets the value of the cantCFEAceptados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantCFEAceptados() {
            return cantCFEAceptados;
        }

        /**
         * Sets the value of the cantCFEAceptados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantCFEAceptados(BigInteger value) {
            this.cantCFEAceptados = value;
        }

        /**
         * Gets the value of the cantCFERechazados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantCFERechazados() {
            return cantCFERechazados;
        }

        /**
         * Sets the value of the cantCFERechazados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantCFERechazados(BigInteger value) {
            this.cantCFERechazados = value;
        }

        /**
         * Gets the value of the cantCFCAceptados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantCFCAceptados() {
            return cantCFCAceptados;
        }

        /**
         * Sets the value of the cantCFCAceptados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantCFCAceptados(BigInteger value) {
            this.cantCFCAceptados = value;
        }

        /**
         * Gets the value of the cantCFCObservados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantCFCObservados() {
            return cantCFCObservados;
        }

        /**
         * Sets the value of the cantCFCObservados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantCFCObservados(BigInteger value) {
            this.cantCFCObservados = value;
        }

        /**
         * Gets the value of the cantOtrosRechazados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantOtrosRechazados() {
            return cantOtrosRechazados;
        }

        /**
         * Sets the value of the cantOtrosRechazados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantOtrosRechazados(BigInteger value) {
            this.cantOtrosRechazados = value;
        }

        /**
         * Gets the value of the tmst property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmst() {
            return tmst;
        }

        /**
         * Sets the value of the tmst property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmst(XMLGregorianCalendar value) {
            this.tmst = value;
        }

    }

}
