//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 02:32:46 PM UYT 
//


package org.openup.dgi.efactura.dto.uy.gub.dgi.cfe;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.openup.dgi.efactura.dto.org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for CAEdefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CAEdefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TmstFrma" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *         &lt;element name="DA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RucE" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="TCFE" type="{http://cfe.dgi.gub.uy}CFEType"/>
 *                   &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
 *                   &lt;element name="DNro">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}NroCFEType">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="HNro">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://cfe.dgi.gub.uy}NroCFEType">
 *                         &lt;minInclusive value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TA" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NA">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="11"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FA" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *                   &lt;element name="FVD" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAEdefType", propOrder = {
    "tmstFrma",
    "da",
    "signature"
})
public class CAEdefType {

    @XmlElement(name = "TmstFrma", required = true)
    protected XMLGregorianCalendar tmstFrma;
    @XmlElement(name = "DA", required = true)
    protected CAEdefType.DA da;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the tmstFrma property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTmstFrma() {
        return tmstFrma;
    }

    /**
     * Sets the value of the tmstFrma property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTmstFrma(XMLGregorianCalendar value) {
        this.tmstFrma = value;
    }

    /**
     * Gets the value of the da property.
     * 
     * @return
     *     possible object is
     *     {@link CAEdefType.DA }
     *     
     */
    public CAEdefType.DA getDA() {
        return da;
    }

    /**
     * Sets the value of the da property.
     * 
     * @param value
     *     allowed object is
     *     {@link CAEdefType.DA }
     *     
     */
    public void setDA(CAEdefType.DA value) {
        this.da = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RucE" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="TCFE" type="{http://cfe.dgi.gub.uy}CFEType"/>
     *         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
     *         &lt;element name="DNro">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}NroCFEType">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="HNro">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://cfe.dgi.gub.uy}NroCFEType">
     *               &lt;minInclusive value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TA" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NA">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="11"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FA" type="{http://cfe.dgi.gub.uy}FechaType"/>
     *         &lt;element name="FVD" type="{http://cfe.dgi.gub.uy}FechaType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rucE",
        "tcfe",
        "serie",
        "dNro",
        "hNro",
        "ta",
        "na",
        "fa",
        "fvd"
    })
    public static class DA {

        @XmlElement(name = "RucE", required = true)
        protected String rucE;
        @XmlElement(name = "TCFE", required = true)
        protected BigInteger tcfe;
        @XmlElement(name = "Serie", required = true)
        protected String serie;
        @XmlElement(name = "DNro", required = true)
        protected BigInteger dNro;
        @XmlElement(name = "HNro", required = true)
        protected BigInteger hNro;
        @XmlElement(name = "TA", required = true)
        protected String ta;
        @XmlElement(name = "NA", required = true)
        protected BigInteger na;
        @XmlElement(name = "FA", required = true)
        protected XMLGregorianCalendar fa;
        @XmlElement(name = "FVD", required = true)
        protected XMLGregorianCalendar fvd;

        /**
         * Gets the value of the rucE property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRucE() {
            return rucE;
        }

        /**
         * Sets the value of the rucE property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRucE(String value) {
            this.rucE = value;
        }

        /**
         * Gets the value of the tcfe property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTCFE() {
            return tcfe;
        }

        /**
         * Sets the value of the tcfe property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTCFE(BigInteger value) {
            this.tcfe = value;
        }

        /**
         * Gets the value of the serie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerie() {
            return serie;
        }

        /**
         * Sets the value of the serie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerie(String value) {
            this.serie = value;
        }

        /**
         * Gets the value of the dNro property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDNro() {
            return dNro;
        }

        /**
         * Sets the value of the dNro property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDNro(BigInteger value) {
            this.dNro = value;
        }

        /**
         * Gets the value of the hNro property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getHNro() {
            return hNro;
        }

        /**
         * Sets the value of the hNro property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setHNro(BigInteger value) {
            this.hNro = value;
        }

        /**
         * Gets the value of the ta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTA() {
            return ta;
        }

        /**
         * Sets the value of the ta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTA(String value) {
            this.ta = value;
        }

        /**
         * Gets the value of the na property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNA() {
            return na;
        }

        /**
         * Sets the value of the na property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNA(BigInteger value) {
            this.na = value;
        }

        /**
         * Gets the value of the fa property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFA() {
            return fa;
        }

        /**
         * Sets the value of the fa property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFA(XMLGregorianCalendar value) {
            this.fa = value;
        }

        /**
         * Gets the value of the fvd property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFVD() {
            return fvd;
        }

        /**
         * Sets the value of the fvd property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFVD(XMLGregorianCalendar value) {
            this.fvd = value;
        }

    }

}
