//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 02:36:07 PM UYT 
//


package org.openup.dgi.efactura.dto.uy.gub.dgi.cfe;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.openup.dgi.efactura.dto.org.w3._2000._09.xmldsig.SignatureType;


/**
 * <p>Java class for CFEsAnuladosdefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFEsAnuladosdefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Caratula">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="RUCReceptor" type="{http://cfe.dgi.gub.uy}RUCType"/>
 *                   &lt;element name="IDComunicacion" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="CantCFEAnulados">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="3"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Tmst" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CFEAnulado" maxOccurs="250">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TipoCFE" type="{http://cfe.dgi.gub.uy}CFEType"/>
 *                   &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
 *                   &lt;element name="NroCFE" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
 *                   &lt;element name="FechaCFE" type="{http://cfe.dgi.gub.uy}FechaType"/>
 *                   &lt;element name="Motivo_Cod">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="2"/>
 *                         &lt;enumeration value="RD"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Motivo_Glosa">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="40"/>
 *                         &lt;enumeration value="Comprobante anulado por rechazo de DGI"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" fixed="1.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="3"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFEsAnuladosdefType", propOrder = {
    "caratula",
    "cfeAnulado",
    "signature"
})
public class CFEsAnuladosdefType {

    @XmlElement(name = "Caratula", required = true)
    protected CFEsAnuladosdefType.Caratula caratula;
    @XmlElement(name = "CFEAnulado", required = true)
    protected List<CFEsAnuladosdefType.CFEAnulado> cfeAnulado;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the caratula property.
     * 
     * @return
     *     possible object is
     *     {@link CFEsAnuladosdefType.Caratula }
     *     
     */
    public CFEsAnuladosdefType.Caratula getCaratula() {
        return caratula;
    }

    /**
     * Sets the value of the caratula property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFEsAnuladosdefType.Caratula }
     *     
     */
    public void setCaratula(CFEsAnuladosdefType.Caratula value) {
        this.caratula = value;
    }

    /**
     * Gets the value of the cfeAnulado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cfeAnulado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCFEAnulado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CFEsAnuladosdefType.CFEAnulado }
     * 
     * 
     */
    public List<CFEsAnuladosdefType.CFEAnulado> getCFEAnulado() {
        if (cfeAnulado == null) {
            cfeAnulado = new ArrayList<CFEsAnuladosdefType.CFEAnulado>();
        }
        return this.cfeAnulado;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.0";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RUCEmisor" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="RUCReceptor" type="{http://cfe.dgi.gub.uy}RUCType"/>
     *         &lt;element name="IDComunicacion" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="CantCFEAnulados">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;totalDigits value="3"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Tmst" type="{http://cfe.dgi.gub.uy}FechaHoraType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rucEmisor",
        "rucReceptor",
        "idComunicacion",
        "cantCFEAnulados",
        "tmst"
    })
    public static class Caratula {

        @XmlElement(name = "RUCEmisor", required = true)
        protected String rucEmisor;
        @XmlElement(name = "RUCReceptor", required = true)
        protected String rucReceptor;
        @XmlElement(name = "IDComunicacion")
        protected BigInteger idComunicacion;
        @XmlElement(name = "CantCFEAnulados", required = true)
        protected BigInteger cantCFEAnulados;
        @XmlElement(name = "Tmst", required = true)
        protected XMLGregorianCalendar tmst;

        /**
         * Gets the value of the rucEmisor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRUCEmisor() {
            return rucEmisor;
        }

        /**
         * Sets the value of the rucEmisor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRUCEmisor(String value) {
            this.rucEmisor = value;
        }

        /**
         * Gets the value of the rucReceptor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRUCReceptor() {
            return rucReceptor;
        }

        /**
         * Sets the value of the rucReceptor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRUCReceptor(String value) {
            this.rucReceptor = value;
        }

        /**
         * Gets the value of the idComunicacion property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getIDComunicacion() {
            return idComunicacion;
        }

        /**
         * Sets the value of the idComunicacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setIDComunicacion(BigInteger value) {
            this.idComunicacion = value;
        }

        /**
         * Gets the value of the cantCFEAnulados property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCantCFEAnulados() {
            return cantCFEAnulados;
        }

        /**
         * Sets the value of the cantCFEAnulados property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCantCFEAnulados(BigInteger value) {
            this.cantCFEAnulados = value;
        }

        /**
         * Gets the value of the tmst property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmst() {
            return tmst;
        }

        /**
         * Sets the value of the tmst property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmst(XMLGregorianCalendar value) {
            this.tmst = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TipoCFE" type="{http://cfe.dgi.gub.uy}CFEType"/>
     *         &lt;element name="Serie" type="{http://cfe.dgi.gub.uy}SerieType"/>
     *         &lt;element name="NroCFE" type="{http://cfe.dgi.gub.uy}NroCFEType"/>
     *         &lt;element name="FechaCFE" type="{http://cfe.dgi.gub.uy}FechaType"/>
     *         &lt;element name="Motivo_Cod">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="2"/>
     *               &lt;enumeration value="RD"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Motivo_Glosa">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="40"/>
     *               &lt;enumeration value="Comprobante anulado por rechazo de DGI"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tipoCFE",
        "serie",
        "nroCFE",
        "fechaCFE",
        "motivoCod",
        "motivoGlosa"
    })
    public static class CFEAnulado {

        @XmlElement(name = "TipoCFE", required = true)
        protected BigInteger tipoCFE;
        @XmlElement(name = "Serie", required = true)
        protected String serie;
        @XmlElement(name = "NroCFE", required = true)
        protected BigInteger nroCFE;
        @XmlElement(name = "FechaCFE", required = true)
        protected XMLGregorianCalendar fechaCFE;
        @XmlElement(name = "Motivo_Cod", required = true)
        protected String motivoCod;
        @XmlElement(name = "Motivo_Glosa", required = true)
        protected String motivoGlosa;

        /**
         * Gets the value of the tipoCFE property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoCFE() {
            return tipoCFE;
        }

        /**
         * Sets the value of the tipoCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoCFE(BigInteger value) {
            this.tipoCFE = value;
        }

        /**
         * Gets the value of the serie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerie() {
            return serie;
        }

        /**
         * Sets the value of the serie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerie(String value) {
            this.serie = value;
        }

        /**
         * Gets the value of the nroCFE property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNroCFE() {
            return nroCFE;
        }

        /**
         * Sets the value of the nroCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNroCFE(BigInteger value) {
            this.nroCFE = value;
        }

        /**
         * Gets the value of the fechaCFE property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaCFE() {
            return fechaCFE;
        }

        /**
         * Sets the value of the fechaCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaCFE(XMLGregorianCalendar value) {
            this.fechaCFE = value;
        }

        /**
         * Gets the value of the motivoCod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMotivoCod() {
            return motivoCod;
        }

        /**
         * Sets the value of the motivoCod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMotivoCod(String value) {
            this.motivoCod = value;
        }

        /**
         * Gets the value of the motivoGlosa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMotivoGlosa() {
            return motivoGlosa;
        }

        /**
         * Sets the value of the motivoGlosa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMotivoGlosa(String value) {
            this.motivoGlosa = value;
        }

    }

}
