//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.18 at 02:39:05 PM UYT 
//


package org.openup.dgi.efactura.dto.uy.gub.dgi.cfe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uy.gub.dgi.cfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Reporte_QNAME = new QName("http://cfe.dgi.gub.uy", "Reporte");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uy.gub.dgi.cfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RngDocsUtil }
     * 
     */
    public RngDocsUtil createRngDocsUtil() {
        return new RngDocsUtil();
    }

    /**
     * Create an instance of {@link RngDocsAnulados }
     * 
     */
    public RngDocsAnulados createRngDocsAnulados() {
        return new RngDocsAnulados();
    }

    /**
     * Create an instance of {@link MontosFyT }
     * 
     */
    public MontosFyT createMontosFyT() {
        return new MontosFyT();
    }

    /**
     * Create an instance of {@link MontosRes }
     * 
     */
    public MontosRes createMontosRes() {
        return new MontosRes();
    }

    /**
     * Create an instance of {@link MontosRem }
     * 
     */
    public MontosRem createMontosRem() {
        return new MontosRem();
    }

    /**
     * Create an instance of {@link MontosRemExp }
     * 
     */
    public MontosRemExp createMontosRemExp() {
        return new MontosRemExp();
    }

    /**
     * Create an instance of {@link MontosFExp }
     * 
     */
    public MontosFExp createMontosFExp() {
        return new MontosFExp();
    }

    /**
     * Create an instance of {@link ReporteDefType }
     * 
     */
    public ReporteDefType createReporteDefType() {
        return new ReporteDefType();
    }

    /**
     * Create an instance of {@link RechazoSobreType }
     * 
     */
    public RechazoSobreType createRechazoSobreType() {
        return new RechazoSobreType();
    }

    /**
     * Create an instance of {@link RsmnDataTck }
     * 
     */
    public RsmnDataTck createRsmnDataTck() {
        return new RsmnDataTck();
    }

    /**
     * Create an instance of {@link RsmnDataResg }
     * 
     */
    public RsmnDataResg createRsmnDataResg() {
        return new RsmnDataResg();
    }

    /**
     * Create an instance of {@link RsmnDataResgCont }
     * 
     */
    public RsmnDataResgCont createRsmnDataResgCont() {
        return new RsmnDataResgCont();
    }

    /**
     * Create an instance of {@link RsmnDataRem }
     * 
     */
    public RsmnDataRem createRsmnDataRem() {
        return new RsmnDataRem();
    }

    /**
     * Create an instance of {@link RsmnDataRemExpCont }
     * 
     */
    public RsmnDataRemExpCont createRsmnDataRemExpCont() {
        return new RsmnDataRemExpCont();
    }

    /**
     * Create an instance of {@link InfoRespOriType }
     * 
     */
    public InfoRespOriType createInfoRespOriType() {
        return new InfoRespOriType();
    }

    /**
     * Create an instance of {@link RsmnDataTckCont }
     * 
     */
    public RsmnDataTckCont createRsmnDataTckCont() {
        return new RsmnDataTckCont();
    }

    /**
     * Create an instance of {@link RsmnDataFacExpCont }
     * 
     */
    public RsmnDataFacExpCont createRsmnDataFacExpCont() {
        return new RsmnDataFacExpCont();
    }

    /**
     * Create an instance of {@link RsmnDataFacCont }
     * 
     */
    public RsmnDataFacCont createRsmnDataFacCont() {
        return new RsmnDataFacCont();
    }

    /**
     * Create an instance of {@link RechazoRepType }
     * 
     */
    public RechazoRepType createRechazoRepType() {
        return new RechazoRepType();
    }

    /**
     * Create an instance of {@link RsmnDataRemCont }
     * 
     */
    public RsmnDataRemCont createRsmnDataRemCont() {
        return new RsmnDataRemCont();
    }

    /**
     * Create an instance of {@link RsmnDataFacExp }
     * 
     */
    public RsmnDataFacExp createRsmnDataFacExp() {
        return new RsmnDataFacExp();
    }

    /**
     * Create an instance of {@link RsmnDataFac }
     * 
     */
    public RsmnDataFac createRsmnDataFac() {
        return new RsmnDataFac();
    }

    /**
     * Create an instance of {@link RsmnDataRemExp }
     * 
     */
    public RsmnDataRemExp createRsmnDataRemExp() {
        return new RsmnDataRemExp();
    }

    /**
     * Create an instance of {@link ObsCFCType }
     * 
     */
    public ObsCFCType createObsCFCType() {
        return new ObsCFCType();
    }

    /**
     * Create an instance of {@link RechazoCFEDGIType }
     * 
     */
    public RechazoCFEDGIType createRechazoCFEDGIType() {
        return new RechazoCFEDGIType();
    }

    /**
     * Create an instance of {@link RechazoCFEPartesType }
     * 
     */
    public RechazoCFEPartesType createRechazoCFEPartesType() {
        return new RechazoCFEPartesType();
    }

    /**
     * Create an instance of {@link RngDocsUtil.RDUItem }
     * 
     */
    public RngDocsUtil.RDUItem createRngDocsUtilRDUItem() {
        return new RngDocsUtil.RDUItem();
    }

    /**
     * Create an instance of {@link RngDocsAnulados.RDAItem }
     * 
     */
    public RngDocsAnulados.RDAItem createRngDocsAnuladosRDAItem() {
        return new RngDocsAnulados.RDAItem();
    }

    /**
     * Create an instance of {@link MontosFyT.MntsFyTItem }
     * 
     */
    public MontosFyT.MntsFyTItem createMontosFyTMntsFyTItem() {
        return new MontosFyT.MntsFyTItem();
    }

    /**
     * Create an instance of {@link MontosRes.MntsResItem }
     * 
     */
    public MontosRes.MntsResItem createMontosResMntsResItem() {
        return new MontosRes.MntsResItem();
    }

    /**
     * Create an instance of {@link MontosRem.MntsRemItem }
     * 
     */
    public MontosRem.MntsRemItem createMontosRemMntsRemItem() {
        return new MontosRem.MntsRemItem();
    }

    /**
     * Create an instance of {@link MontosRemExp.MntsRemExpItem }
     * 
     */
    public MontosRemExp.MntsRemExpItem createMontosRemExpMntsRemExpItem() {
        return new MontosRemExp.MntsRemExpItem();
    }

    /**
     * Create an instance of {@link MontosFExp.MntsFExpItem }
     * 
     */
    public MontosFExp.MntsFExpItem createMontosFExpMntsFExpItem() {
        return new MontosFExp.MntsFExpItem();
    }

    /**
     * Create an instance of {@link ReporteDefType.Caratula }
     * 
     */
    public ReporteDefType.Caratula createReporteDefTypeCaratula() {
        return new ReporteDefType.Caratula();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTck }
     * 
     */
    public ReporteDefType.RsmnTck createReporteDefTypeRsmnTck() {
        return new ReporteDefType.RsmnTck();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckNotaCredito }
     * 
     */
    public ReporteDefType.RsmnTckNotaCredito createReporteDefTypeRsmnTckNotaCredito() {
        return new ReporteDefType.RsmnTckNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckNotaDebito }
     * 
     */
    public ReporteDefType.RsmnTckNotaDebito createReporteDefTypeRsmnTckNotaDebito() {
        return new ReporteDefType.RsmnTckNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckCont }
     * 
     */
    public ReporteDefType.RsmnTckCont createReporteDefTypeRsmnTckCont() {
        return new ReporteDefType.RsmnTckCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckContNotaCredito }
     * 
     */
    public ReporteDefType.RsmnTckContNotaCredito createReporteDefTypeRsmnTckContNotaCredito() {
        return new ReporteDefType.RsmnTckContNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckContNotaDebito }
     * 
     */
    public ReporteDefType.RsmnTckContNotaDebito createReporteDefTypeRsmnTckContNotaDebito() {
        return new ReporteDefType.RsmnTckContNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckCtaAj }
     * 
     */
    public ReporteDefType.RsmnTckCtaAj createReporteDefTypeRsmnTckCtaAj() {
        return new ReporteDefType.RsmnTckCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckNotaCreditoCtaAj }
     * 
     */
    public ReporteDefType.RsmnTckNotaCreditoCtaAj createReporteDefTypeRsmnTckNotaCreditoCtaAj() {
        return new ReporteDefType.RsmnTckNotaCreditoCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckNotaDebitoCtaAj }
     * 
     */
    public ReporteDefType.RsmnTckNotaDebitoCtaAj createReporteDefTypeRsmnTckNotaDebitoCtaAj() {
        return new ReporteDefType.RsmnTckNotaDebitoCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckCtaAjCont }
     * 
     */
    public ReporteDefType.RsmnTckCtaAjCont createReporteDefTypeRsmnTckCtaAjCont() {
        return new ReporteDefType.RsmnTckCtaAjCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckCtaAjContNotaCredito }
     * 
     */
    public ReporteDefType.RsmnTckCtaAjContNotaCredito createReporteDefTypeRsmnTckCtaAjContNotaCredito() {
        return new ReporteDefType.RsmnTckCtaAjContNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnTckCtaAjContNotaDebito }
     * 
     */
    public ReporteDefType.RsmnTckCtaAjContNotaDebito createReporteDefTypeRsmnTckCtaAjContNotaDebito() {
        return new ReporteDefType.RsmnTckCtaAjContNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFac }
     * 
     */
    public ReporteDefType.RsmnFac createReporteDefTypeRsmnFac() {
        return new ReporteDefType.RsmnFac();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacNotaCredito }
     * 
     */
    public ReporteDefType.RsmnFacNotaCredito createReporteDefTypeRsmnFacNotaCredito() {
        return new ReporteDefType.RsmnFacNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacNotaDebito }
     * 
     */
    public ReporteDefType.RsmnFacNotaDebito createReporteDefTypeRsmnFacNotaDebito() {
        return new ReporteDefType.RsmnFacNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacCont }
     * 
     */
    public ReporteDefType.RsmnFacCont createReporteDefTypeRsmnFacCont() {
        return new ReporteDefType.RsmnFacCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacContNotaCredito }
     * 
     */
    public ReporteDefType.RsmnFacContNotaCredito createReporteDefTypeRsmnFacContNotaCredito() {
        return new ReporteDefType.RsmnFacContNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacContNotaDebito }
     * 
     */
    public ReporteDefType.RsmnFacContNotaDebito createReporteDefTypeRsmnFacContNotaDebito() {
        return new ReporteDefType.RsmnFacContNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacCtaAj }
     * 
     */
    public ReporteDefType.RsmnFacCtaAj createReporteDefTypeRsmnFacCtaAj() {
        return new ReporteDefType.RsmnFacCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacNotaCreditoCtaAj }
     * 
     */
    public ReporteDefType.RsmnFacNotaCreditoCtaAj createReporteDefTypeRsmnFacNotaCreditoCtaAj() {
        return new ReporteDefType.RsmnFacNotaCreditoCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacNotaDebitoCtaAj }
     * 
     */
    public ReporteDefType.RsmnFacNotaDebitoCtaAj createReporteDefTypeRsmnFacNotaDebitoCtaAj() {
        return new ReporteDefType.RsmnFacNotaDebitoCtaAj();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacCtaAjCont }
     * 
     */
    public ReporteDefType.RsmnFacCtaAjCont createReporteDefTypeRsmnFacCtaAjCont() {
        return new ReporteDefType.RsmnFacCtaAjCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacCtaAjContNotaCredito }
     * 
     */
    public ReporteDefType.RsmnFacCtaAjContNotaCredito createReporteDefTypeRsmnFacCtaAjContNotaCredito() {
        return new ReporteDefType.RsmnFacCtaAjContNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacCtaAjContNotaDebito }
     * 
     */
    public ReporteDefType.RsmnFacCtaAjContNotaDebito createReporteDefTypeRsmnFacCtaAjContNotaDebito() {
        return new ReporteDefType.RsmnFacCtaAjContNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExp }
     * 
     */
    public ReporteDefType.RsmnFacExp createReporteDefTypeRsmnFacExp() {
        return new ReporteDefType.RsmnFacExp();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExpNotaCredito }
     * 
     */
    public ReporteDefType.RsmnFacExpNotaCredito createReporteDefTypeRsmnFacExpNotaCredito() {
        return new ReporteDefType.RsmnFacExpNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExpNotaDebito }
     * 
     */
    public ReporteDefType.RsmnFacExpNotaDebito createReporteDefTypeRsmnFacExpNotaDebito() {
        return new ReporteDefType.RsmnFacExpNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExpCont }
     * 
     */
    public ReporteDefType.RsmnFacExpCont createReporteDefTypeRsmnFacExpCont() {
        return new ReporteDefType.RsmnFacExpCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExpContNotaCredito }
     * 
     */
    public ReporteDefType.RsmnFacExpContNotaCredito createReporteDefTypeRsmnFacExpContNotaCredito() {
        return new ReporteDefType.RsmnFacExpContNotaCredito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnFacExpContNotaDebito }
     * 
     */
    public ReporteDefType.RsmnFacExpContNotaDebito createReporteDefTypeRsmnFacExpContNotaDebito() {
        return new ReporteDefType.RsmnFacExpContNotaDebito();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnRem }
     * 
     */
    public ReporteDefType.RsmnRem createReporteDefTypeRsmnRem() {
        return new ReporteDefType.RsmnRem();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnRemCont }
     * 
     */
    public ReporteDefType.RsmnRemCont createReporteDefTypeRsmnRemCont() {
        return new ReporteDefType.RsmnRemCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnRemExp }
     * 
     */
    public ReporteDefType.RsmnRemExp createReporteDefTypeRsmnRemExp() {
        return new ReporteDefType.RsmnRemExp();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnRemExpCont }
     * 
     */
    public ReporteDefType.RsmnRemExpCont createReporteDefTypeRsmnRemExpCont() {
        return new ReporteDefType.RsmnRemExpCont();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnResg }
     * 
     */
    public ReporteDefType.RsmnResg createReporteDefTypeRsmnResg() {
        return new ReporteDefType.RsmnResg();
    }

    /**
     * Create an instance of {@link ReporteDefType.RsmnResgCont }
     * 
     */
    public ReporteDefType.RsmnResgCont createReporteDefTypeRsmnResgCont() {
        return new ReporteDefType.RsmnResgCont();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReporteDefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cfe.dgi.gub.uy", name = "Reporte")
    public JAXBElement<ReporteDefType> createReporte(ReporteDefType value) {
        return new JAXBElement<ReporteDefType>(_Reporte_QNAME, ReporteDefType.class, null, value);
    }

}
