//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:44:41 PM UYT 
//


package org.openup.dgi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openup.dgi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openup.dgi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem createEnvioCFECFECFEItem() {
        return new EnvioCFE.CFE.CFEItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep.RetencPercepItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep.RetencPercepItem createEnvioCFECFECFEItemDetalleItemRetencPercepRetencPercepItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep.RetencPercepItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem.CodItemItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem.CodItemItem createEnvioCFECFECFEItemDetalleItemCodItemCodItemItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem.CodItemItem();
    }

    /**
     * Create an instance of {@link EnvioCFE }
     * 
     */
    public EnvioCFE createEnvioCFE() {
        return new EnvioCFE();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot createEnvioCFECFECFEItemTotalesRetencPercepTot() {
        return new EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Receptor }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Receptor createEnvioCFECFECFEItemReceptor() {
        return new EnvioCFE.CFE.CFEItem.Receptor();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo createEnvioCFECFECFEItemDetalleItemSubRecargo() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot.RetencPercepTotItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot.RetencPercepTotItem createEnvioCFECFECFEItemTotalesRetencPercepTotRetencPercepTotItem() {
        return new EnvioCFE.CFE.CFEItem.Totales.RetencPercepTot.RetencPercepTotItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE }
     * 
     */
    public EnvioCFE.CFE createEnvioCFECFE() {
        return new EnvioCFE.CFE();
    }

    /**
     * Create an instance of {@link ObsCFCType }
     * 
     */
    public ObsCFCType createObsCFCType() {
        return new ObsCFCType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.SubTotInfo.STIItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.SubTotInfo.STIItem createEnvioCFECFECFEItemSubTotInfoSTIItem() {
        return new EnvioCFE.CFE.CFEItem.SubTotInfo.STIItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle createEnvioCFECFECFEItemDetalle() {
        return new EnvioCFE.CFE.CFEItem.Detalle();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem createEnvioCFECFECFEItemDetalleItemCodItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.CodItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.DscRcgGlobal.DRGItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.DscRcgGlobal.DRGItem createEnvioCFECFECFEItemDscRcgGlobalDRGItem() {
        return new EnvioCFE.CFE.CFEItem.DscRcgGlobal.DRGItem();
    }

    /**
     * Create an instance of {@link RechazoCFEDGIType }
     * 
     */
    public RechazoCFEDGIType createRechazoCFEDGIType() {
        return new RechazoCFEDGIType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Referencia }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Referencia createEnvioCFECFECFEItemReferencia() {
        return new EnvioCFE.CFE.CFEItem.Referencia();
    }

    /**
     * Create an instance of {@link RechazoSobreType }
     * 
     */
    public RechazoSobreType createRechazoSobreType() {
        return new RechazoSobreType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item createEnvioCFECFECFEItemDetalleItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento createEnvioCFECFECFEItemDetalleItemSubDescuento() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Totales }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Totales createEnvioCFECFECFEItemTotales() {
        return new EnvioCFE.CFE.CFEItem.Totales();
    }

    /**
     * Create an instance of {@link RechazoCFEPartesType }
     * 
     */
    public RechazoCFEPartesType createRechazoCFEPartesType() {
        return new RechazoCFEPartesType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.SubTotInfo }
     * 
     */
    public EnvioCFE.CFE.CFEItem.SubTotInfo createEnvioCFECFECFEItemSubTotInfo() {
        return new EnvioCFE.CFE.CFEItem.SubTotInfo();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo.SubRecargoItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo.SubRecargoItem createEnvioCFECFECFEItemDetalleItemSubRecargoSubRecargoItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.SubRecargo.SubRecargoItem();
    }

    /**
     * Create an instance of {@link InfoRespOriType }
     * 
     */
    public InfoRespOriType createInfoRespOriType() {
        return new InfoRespOriType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.MediosPago.MediosPagoItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.MediosPago.MediosPagoItem createEnvioCFECFECFEItemMediosPagoMediosPagoItem() {
        return new EnvioCFE.CFE.CFEItem.MediosPago.MediosPagoItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento.SubDescuentoItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento.SubDescuentoItem createEnvioCFECFECFEItemDetalleItemSubDescuentoSubDescuentoItem() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.SubDescuento.SubDescuentoItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Emisor }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Emisor createEnvioCFECFECFEItemEmisor() {
        return new EnvioCFE.CFE.CFEItem.Emisor();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.MediosPago }
     * 
     */
    public EnvioCFE.CFE.CFEItem.MediosPago createEnvioCFECFECFEItemMediosPago() {
        return new EnvioCFE.CFE.CFEItem.MediosPago();
    }

    /**
     * Create an instance of {@link EnvioCFE.Encabezado }
     * 
     */
    public EnvioCFE.Encabezado createEnvioCFEEncabezado() {
        return new EnvioCFE.Encabezado();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Referencia.ReferenciaItem }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Referencia.ReferenciaItem createEnvioCFECFECFEItemReferenciaReferenciaItem() {
        return new EnvioCFE.CFE.CFEItem.Referencia.ReferenciaItem();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep }
     * 
     */
    public EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep createEnvioCFECFECFEItemDetalleItemRetencPercep() {
        return new EnvioCFE.CFE.CFEItem.Detalle.Item.RetencPercep();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.DscRcgGlobal }
     * 
     */
    public EnvioCFE.CFE.CFEItem.DscRcgGlobal createEnvioCFECFECFEItemDscRcgGlobal() {
        return new EnvioCFE.CFE.CFEItem.DscRcgGlobal();
    }

    /**
     * Create an instance of {@link RechazoRepType }
     * 
     */
    public RechazoRepType createRechazoRepType() {
        return new RechazoRepType();
    }

    /**
     * Create an instance of {@link EnvioCFE.CFE.CFEItem.IdDoc }
     * 
     */
    public EnvioCFE.CFE.CFEItem.IdDoc createEnvioCFECFECFEItemIdDoc() {
        return new EnvioCFE.CFE.CFEItem.IdDoc();
    }

}
