//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:44:41 PM UYT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "www.invoicy.com.uy", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openup.dgi;
