//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.25 at 12:44:19 PM UYT 
//


package org.openup.dgi;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EnvioCFERetorno">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Encabezado">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EmpCodigo" type="{www.invoicy.com.uy}EmpCodigoType"/>
 *                             &lt;element name="NroLinRetorno" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="MsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                             &lt;element name="MsgDsc" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="4000"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ListaCFE" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CFE" maxOccurs="99999">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="CFETipo" type="{www.invoicy.com.uy}CFEType"/>
 *                                       &lt;element name="CFESerie" type="{www.invoicy.com.uy}SerieType"/>
 *                                       &lt;element name="CFENro" type="{www.invoicy.com.uy}NroCFEType"/>
 *                                       &lt;element name="CFEStatus" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                             &lt;enumeration value="1"/>
 *                                             &lt;enumeration value="2"/>
 *                                             &lt;enumeration value="3"/>
 *                                             &lt;enumeration value="4"/>
 *                                             &lt;enumeration value="5"/>
 *                                             &lt;enumeration value="6"/>
 *                                             &lt;enumeration value="7"/>
 *                                             &lt;enumeration value="8"/>
 *                                             &lt;enumeration value="9"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFEEstadoAcuse" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                                             &lt;enumeration value="1"/>
 *                                             &lt;enumeration value="2"/>
 *                                             &lt;enumeration value="3"/>
 *                                             &lt;enumeration value="4"/>
 *                                             &lt;enumeration value="5"/>
 *                                             &lt;enumeration value="6"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFEMsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                                       &lt;element name="CFEMsgDsc" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="4000"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFEXMLEE" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="500000"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFERepImpressa" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="500000"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFEQrCode" minOccurs="0">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="500000"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="CFEFechaHoraConsulta" type="{www.invoicy.com.uy}FechaHoraType" minOccurs="0"/>
 *                                       &lt;element name="CFENumReferencia">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;minLength value="1"/>
 *                                             &lt;maxLength value="7"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Erros" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                                           &lt;element name="CFEErrDesc">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                 &lt;maxLength value="4000"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="ErrosDGI" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="CFERetCod">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                 &lt;maxLength value="3"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                           &lt;element name="CFERetDesc">
 *                                                             &lt;simpleType>
 *                                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                                 &lt;maxLength value="4000"/>
 *                                                               &lt;/restriction>
 *                                                             &lt;/simpleType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "envioCFERetorno"
})
@XmlRootElement(name = "Xmlretorno")
public class Xmlretorno {

    @XmlElement(name = "EnvioCFERetorno", required = true)
    protected Xmlretorno.EnvioCFERetorno envioCFERetorno;

    /**
     * Gets the value of the envioCFERetorno property.
     * 
     * @return
     *     possible object is
     *     {@link Xmlretorno.EnvioCFERetorno }
     *     
     */
    public Xmlretorno.EnvioCFERetorno getEnvioCFERetorno() {
        return envioCFERetorno;
    }

    /**
     * Sets the value of the envioCFERetorno property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xmlretorno.EnvioCFERetorno }
     *     
     */
    public void setEnvioCFERetorno(Xmlretorno.EnvioCFERetorno value) {
        this.envioCFERetorno = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Encabezado">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EmpCodigo" type="{www.invoicy.com.uy}EmpCodigoType"/>
     *                   &lt;element name="NroLinRetorno" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="MsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                   &lt;element name="MsgDsc" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="4000"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ListaCFE" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CFE" maxOccurs="99999">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CFETipo" type="{www.invoicy.com.uy}CFEType"/>
     *                             &lt;element name="CFESerie" type="{www.invoicy.com.uy}SerieType"/>
     *                             &lt;element name="CFENro" type="{www.invoicy.com.uy}NroCFEType"/>
     *                             &lt;element name="CFEStatus" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                                   &lt;enumeration value="1"/>
     *                                   &lt;enumeration value="2"/>
     *                                   &lt;enumeration value="3"/>
     *                                   &lt;enumeration value="4"/>
     *                                   &lt;enumeration value="5"/>
     *                                   &lt;enumeration value="6"/>
     *                                   &lt;enumeration value="7"/>
     *                                   &lt;enumeration value="8"/>
     *                                   &lt;enumeration value="9"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFEEstadoAcuse" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *                                   &lt;enumeration value="1"/>
     *                                   &lt;enumeration value="2"/>
     *                                   &lt;enumeration value="3"/>
     *                                   &lt;enumeration value="4"/>
     *                                   &lt;enumeration value="5"/>
     *                                   &lt;enumeration value="6"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFEMsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *                             &lt;element name="CFEMsgDsc" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="4000"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFEXMLEE" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="500000"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFERepImpressa" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="500000"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFEQrCode" minOccurs="0">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="500000"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="CFEFechaHoraConsulta" type="{www.invoicy.com.uy}FechaHoraType" minOccurs="0"/>
     *                             &lt;element name="CFENumReferencia">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;minLength value="1"/>
     *                                   &lt;maxLength value="7"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Erros" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                                                 &lt;element name="CFEErrDesc">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                                       &lt;maxLength value="4000"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="ErrosDGI" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="CFERetCod">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                                       &lt;maxLength value="3"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                                 &lt;element name="CFERetDesc">
     *                                                   &lt;simpleType>
     *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                                       &lt;maxLength value="4000"/>
     *                                                     &lt;/restriction>
     *                                                   &lt;/simpleType>
     *                                                 &lt;/element>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encabezado",
        "listaCFE"
    })
    public static class EnvioCFERetorno {

        @XmlElement(name = "Encabezado", required = true)
        protected Xmlretorno.EnvioCFERetorno.Encabezado encabezado;
        @XmlElement(name = "ListaCFE")
        protected Xmlretorno.EnvioCFERetorno.ListaCFE listaCFE;

        /**
         * Gets the value of the encabezado property.
         * 
         * @return
         *     possible object is
         *     {@link Xmlretorno.EnvioCFERetorno.Encabezado }
         *     
         */
        public Xmlretorno.EnvioCFERetorno.Encabezado getEncabezado() {
            return encabezado;
        }

        /**
         * Sets the value of the encabezado property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xmlretorno.EnvioCFERetorno.Encabezado }
         *     
         */
        public void setEncabezado(Xmlretorno.EnvioCFERetorno.Encabezado value) {
            this.encabezado = value;
        }

        /**
         * Gets the value of the listaCFE property.
         * 
         * @return
         *     possible object is
         *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE }
         *     
         */
        public Xmlretorno.EnvioCFERetorno.ListaCFE getListaCFE() {
            return listaCFE;
        }

        /**
         * Sets the value of the listaCFE property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE }
         *     
         */
        public void setListaCFE(Xmlretorno.EnvioCFERetorno.ListaCFE value) {
            this.listaCFE = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EmpCodigo" type="{www.invoicy.com.uy}EmpCodigoType"/>
         *         &lt;element name="NroLinRetorno" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="MsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *         &lt;element name="MsgDsc" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="4000"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "empCodigo",
            "nroLinRetorno",
            "msgCod",
            "msgDsc"
        })
        public static class Encabezado {

            @XmlElement(name = "EmpCodigo", required = true)
            protected String empCodigo;
            @XmlElement(name = "NroLinRetorno", required = true)
            protected BigInteger nroLinRetorno;
            @XmlElement(name = "MsgCod")
            protected BigInteger msgCod;
            @XmlElement(name = "MsgDsc")
            protected String msgDsc;

            /**
             * Gets the value of the empCodigo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEmpCodigo() {
                return empCodigo;
            }

            /**
             * Sets the value of the empCodigo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEmpCodigo(String value) {
                this.empCodigo = value;
            }

            /**
             * Gets the value of the nroLinRetorno property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNroLinRetorno() {
                return nroLinRetorno;
            }

            /**
             * Sets the value of the nroLinRetorno property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNroLinRetorno(BigInteger value) {
                this.nroLinRetorno = value;
            }

            /**
             * Gets the value of the msgCod property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMsgCod() {
                return msgCod;
            }

            /**
             * Sets the value of the msgCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMsgCod(BigInteger value) {
                this.msgCod = value;
            }

            /**
             * Gets the value of the msgDsc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMsgDsc() {
                return msgDsc;
            }

            /**
             * Sets the value of the msgDsc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMsgDsc(String value) {
                this.msgDsc = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CFE" maxOccurs="99999">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CFETipo" type="{www.invoicy.com.uy}CFEType"/>
         *                   &lt;element name="CFESerie" type="{www.invoicy.com.uy}SerieType"/>
         *                   &lt;element name="CFENro" type="{www.invoicy.com.uy}NroCFEType"/>
         *                   &lt;element name="CFEStatus" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *                         &lt;enumeration value="1"/>
         *                         &lt;enumeration value="2"/>
         *                         &lt;enumeration value="3"/>
         *                         &lt;enumeration value="4"/>
         *                         &lt;enumeration value="5"/>
         *                         &lt;enumeration value="6"/>
         *                         &lt;enumeration value="7"/>
         *                         &lt;enumeration value="8"/>
         *                         &lt;enumeration value="9"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFEEstadoAcuse" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
         *                         &lt;enumeration value="1"/>
         *                         &lt;enumeration value="2"/>
         *                         &lt;enumeration value="3"/>
         *                         &lt;enumeration value="4"/>
         *                         &lt;enumeration value="5"/>
         *                         &lt;enumeration value="6"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFEMsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
         *                   &lt;element name="CFEMsgDsc" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="4000"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFEXMLEE" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="500000"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFERepImpressa" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="500000"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFEQrCode" minOccurs="0">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="500000"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="CFEFechaHoraConsulta" type="{www.invoicy.com.uy}FechaHoraType" minOccurs="0"/>
         *                   &lt;element name="CFENumReferencia">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;minLength value="1"/>
         *                         &lt;maxLength value="7"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Erros" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                                       &lt;element name="CFEErrDesc">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                             &lt;maxLength value="4000"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="ErrosDGI" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="CFERetCod">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                             &lt;maxLength value="3"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                       &lt;element name="CFERetDesc">
         *                                         &lt;simpleType>
         *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                             &lt;maxLength value="4000"/>
         *                                           &lt;/restriction>
         *                                         &lt;/simpleType>
         *                                       &lt;/element>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cfe"
        })
        public static class ListaCFE {

            @XmlElement(name = "CFE", required = true)
            protected List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE> cfe;

            /**
             * Gets the value of the cfe property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the cfe property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCFE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE }
             * 
             * 
             */
            public List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE> getCFE() {
                if (cfe == null) {
                    cfe = new ArrayList<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE>();
                }
                return this.cfe;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CFETipo" type="{www.invoicy.com.uy}CFEType"/>
             *         &lt;element name="CFESerie" type="{www.invoicy.com.uy}SerieType"/>
             *         &lt;element name="CFENro" type="{www.invoicy.com.uy}NroCFEType"/>
             *         &lt;element name="CFEStatus" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
             *               &lt;enumeration value="1"/>
             *               &lt;enumeration value="2"/>
             *               &lt;enumeration value="3"/>
             *               &lt;enumeration value="4"/>
             *               &lt;enumeration value="5"/>
             *               &lt;enumeration value="6"/>
             *               &lt;enumeration value="7"/>
             *               &lt;enumeration value="8"/>
             *               &lt;enumeration value="9"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFEEstadoAcuse" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
             *               &lt;enumeration value="1"/>
             *               &lt;enumeration value="2"/>
             *               &lt;enumeration value="3"/>
             *               &lt;enumeration value="4"/>
             *               &lt;enumeration value="5"/>
             *               &lt;enumeration value="6"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFEMsgCod" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
             *         &lt;element name="CFEMsgDsc" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="4000"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFEXMLEE" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="500000"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFERepImpressa" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="500000"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFEQrCode" minOccurs="0">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="500000"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="CFEFechaHoraConsulta" type="{www.invoicy.com.uy}FechaHoraType" minOccurs="0"/>
             *         &lt;element name="CFENumReferencia">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;minLength value="1"/>
             *               &lt;maxLength value="7"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Erros" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *                             &lt;element name="CFEErrDesc">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                                   &lt;maxLength value="4000"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="ErrosDGI" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="CFERetCod">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                                   &lt;maxLength value="3"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                             &lt;element name="CFERetDesc">
             *                               &lt;simpleType>
             *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                                   &lt;maxLength value="4000"/>
             *                                 &lt;/restriction>
             *                               &lt;/simpleType>
             *                             &lt;/element>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "cfeTipo",
                "cfeSerie",
                "cfeNro",
                "cfeStatus",
                "cfeEstadoAcuse",
                "cfeMsgCod",
                "cfeMsgDsc",
                "cfexmlee",
                "cfeRepImpressa",
                "cfeQrCode",
                "cfeFechaHoraConsulta",
                "cfeNumReferencia",
                "erros",
                "errosDGI"
            })
            public static class CFE {

                @XmlElement(name = "CFETipo", required = true)
                protected BigInteger cfeTipo;
                @XmlElement(name = "CFESerie", required = true)
                protected String cfeSerie;
                @XmlElement(name = "CFENro", required = true)
                protected BigInteger cfeNro;
                @XmlElement(name = "CFEStatus")
                protected BigInteger cfeStatus;
                @XmlElement(name = "CFEEstadoAcuse")
                protected BigInteger cfeEstadoAcuse;
                @XmlElement(name = "CFEMsgCod")
                protected BigInteger cfeMsgCod;
                @XmlElement(name = "CFEMsgDsc")
                protected String cfeMsgDsc;
                @XmlElement(name = "CFEXMLEE")
                protected String cfexmlee;
                @XmlElement(name = "CFERepImpressa")
                protected String cfeRepImpressa;
                @XmlElement(name = "CFEQrCode")
                protected String cfeQrCode;
                @XmlElement(name = "CFEFechaHoraConsulta")
                protected XMLGregorianCalendar cfeFechaHoraConsulta;
                @XmlElement(name = "CFENumReferencia", required = true)
                protected String cfeNumReferencia;
                @XmlElement(name = "Erros")
                protected Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros erros;
                @XmlElement(name = "ErrosDGI")
                protected Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI errosDGI;

                /**
                 * Gets the value of the cfeTipo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCFETipo() {
                    return cfeTipo;
                }

                /**
                 * Sets the value of the cfeTipo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCFETipo(BigInteger value) {
                    this.cfeTipo = value;
                }

                /**
                 * Gets the value of the cfeSerie property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFESerie() {
                    return cfeSerie;
                }

                /**
                 * Sets the value of the cfeSerie property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFESerie(String value) {
                    this.cfeSerie = value;
                }

                /**
                 * Gets the value of the cfeNro property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCFENro() {
                    return cfeNro;
                }

                /**
                 * Sets the value of the cfeNro property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCFENro(BigInteger value) {
                    this.cfeNro = value;
                }

                /**
                 * Gets the value of the cfeStatus property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCFEStatus() {
                    return cfeStatus;
                }

                /**
                 * Sets the value of the cfeStatus property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCFEStatus(BigInteger value) {
                    this.cfeStatus = value;
                }

                /**
                 * Gets the value of the cfeEstadoAcuse property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCFEEstadoAcuse() {
                    return cfeEstadoAcuse;
                }

                /**
                 * Sets the value of the cfeEstadoAcuse property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCFEEstadoAcuse(BigInteger value) {
                    this.cfeEstadoAcuse = value;
                }

                /**
                 * Gets the value of the cfeMsgCod property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getCFEMsgCod() {
                    return cfeMsgCod;
                }

                /**
                 * Sets the value of the cfeMsgCod property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setCFEMsgCod(BigInteger value) {
                    this.cfeMsgCod = value;
                }

                /**
                 * Gets the value of the cfeMsgDsc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFEMsgDsc() {
                    return cfeMsgDsc;
                }

                /**
                 * Sets the value of the cfeMsgDsc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFEMsgDsc(String value) {
                    this.cfeMsgDsc = value;
                }

                /**
                 * Gets the value of the cfexmlee property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFEXMLEE() {
                    return cfexmlee;
                }

                /**
                 * Sets the value of the cfexmlee property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFEXMLEE(String value) {
                    this.cfexmlee = value;
                }

                /**
                 * Gets the value of the cfeRepImpressa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFERepImpressa() {
                    return cfeRepImpressa;
                }

                /**
                 * Sets the value of the cfeRepImpressa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFERepImpressa(String value) {
                    this.cfeRepImpressa = value;
                }

                /**
                 * Gets the value of the cfeQrCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFEQrCode() {
                    return cfeQrCode;
                }

                /**
                 * Sets the value of the cfeQrCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFEQrCode(String value) {
                    this.cfeQrCode = value;
                }

                /**
                 * Gets the value of the cfeFechaHoraConsulta property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public XMLGregorianCalendar getCFEFechaHoraConsulta() {
                    return cfeFechaHoraConsulta;
                }

                /**
                 * Sets the value of the cfeFechaHoraConsulta property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link XMLGregorianCalendar }
                 *     
                 */
                public void setCFEFechaHoraConsulta(XMLGregorianCalendar value) {
                    this.cfeFechaHoraConsulta = value;
                }

                /**
                 * Gets the value of the cfeNumReferencia property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCFENumReferencia() {
                    return cfeNumReferencia;
                }

                /**
                 * Sets the value of the cfeNumReferencia property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCFENumReferencia(String value) {
                    this.cfeNumReferencia = value;
                }

                /**
                 * Gets the value of the erros property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros }
                 *     
                 */
                public Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros getErros() {
                    return erros;
                }

                /**
                 * Sets the value of the erros property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros }
                 *     
                 */
                public void setErros(Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros value) {
                    this.erros = value;
                }

                /**
                 * Gets the value of the errosDGI property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI }
                 *     
                 */
                public Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI getErrosDGI() {
                    return errosDGI;
                }

                /**
                 * Sets the value of the errosDGI property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI }
                 *     
                 */
                public void setErrosDGI(Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI value) {
                    this.errosDGI = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ErrosItem" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                 *                   &lt;element name="CFEErrDesc">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *                         &lt;maxLength value="4000"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errosItem"
                })
                public static class Erros {

                    @XmlElement(name = "ErrosItem")
                    protected List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros.ErrosItem> errosItem;

                    /**
                     * Gets the value of the errosItem property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the errosItem property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getErrosItem().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros.ErrosItem }
                     * 
                     * 
                     */
                    public List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros.ErrosItem> getErrosItem() {
                        if (errosItem == null) {
                            errosItem = new ArrayList<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.Erros.ErrosItem>();
                        }
                        return this.errosItem;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="CFEErrCod" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                     *         &lt;element name="CFEErrDesc">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;maxLength value="4000"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "cfeErrCod",
                        "cfeErrDesc"
                    })
                    public static class ErrosItem {

                        @XmlElement(name = "CFEErrCod", required = true)
                        protected BigInteger cfeErrCod;
                        @XmlElement(name = "CFEErrDesc", required = true)
                        protected String cfeErrDesc;

                        /**
                         * Gets the value of the cfeErrCod property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigInteger }
                         *     
                         */
                        public BigInteger getCFEErrCod() {
                            return cfeErrCod;
                        }

                        /**
                         * Sets the value of the cfeErrCod property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigInteger }
                         *     
                         */
                        public void setCFEErrCod(BigInteger value) {
                            this.cfeErrCod = value;
                        }

                        /**
                         * Gets the value of the cfeErrDesc property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCFEErrDesc() {
                            return cfeErrDesc;
                        }

                        /**
                         * Sets the value of the cfeErrDesc property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCFEErrDesc(String value) {
                            this.cfeErrDesc = value;
                        }

                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ErrosDGIItem" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="CFERetCod">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *                         &lt;maxLength value="3"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                   &lt;element name="CFERetDesc">
                 *                     &lt;simpleType>
                 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *                         &lt;maxLength value="4000"/>
                 *                       &lt;/restriction>
                 *                     &lt;/simpleType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "errosDGIItem"
                })
                public static class ErrosDGI {

                    @XmlElement(name = "ErrosDGIItem")
                    protected List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI.ErrosDGIItem> errosDGIItem;

                    /**
                     * Gets the value of the errosDGIItem property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the errosDGIItem property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getErrosDGIItem().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI.ErrosDGIItem }
                     * 
                     * 
                     */
                    public List<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI.ErrosDGIItem> getErrosDGIItem() {
                        if (errosDGIItem == null) {
                            errosDGIItem = new ArrayList<Xmlretorno.EnvioCFERetorno.ListaCFE.CFE.ErrosDGI.ErrosDGIItem>();
                        }
                        return this.errosDGIItem;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="CFERetCod">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;maxLength value="3"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="CFERetDesc">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;maxLength value="4000"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "cfeRetCod",
                        "cfeRetDesc"
                    })
                    public static class ErrosDGIItem {

                        @XmlElement(name = "CFERetCod", required = true)
                        protected String cfeRetCod;
                        @XmlElement(name = "CFERetDesc", required = true)
                        protected String cfeRetDesc;

                        /**
                         * Gets the value of the cfeRetCod property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCFERetCod() {
                            return cfeRetCod;
                        }

                        /**
                         * Sets the value of the cfeRetCod property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCFERetCod(String value) {
                            this.cfeRetCod = value;
                        }

                        /**
                         * Gets the value of the cfeRetDesc property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getCFERetDesc() {
                            return cfeRetDesc;
                        }

                        /**
                         * Sets the value of the cfeRetDesc property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setCFERetDesc(String value) {
                            this.cfeRetDesc = value;
                        }

                    }

                }

            }

        }

    }

}
